//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace trenimLast
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class trenimLastEntities : DbContext
    {
        public trenimLastEntities()
            : base("name=trenimLastEntities")
        {
        }
        private static trenimLastEntities _context;
        public static trenimLastEntities GetContext()
        {
            if (_context == null)
                _context = new trenimLastEntities();
            return _context;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Categorys> Categorys { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<OrdersProducts> OrdersProducts { get; set; }
        public virtual DbSet<PickUpPoint> PickUpPoint { get; set; }
        public virtual DbSet<Porducts> Porducts { get; set; }
        public virtual DbSet<Rolys> Rolys { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
