//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace trenimLast
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdersProducts
    {
        public int orders { get; set; }
        public string artucul { get; set; }
        public int count { get; set; }
    
        public virtual Orders Orders1 { get; set; }
        public virtual Porducts Porducts { get; set; }
    }
}
