//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace trenimLast
{
    using System;
    using System.Collections.Generic;
    using System.Windows;

    public partial class Porducts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Porducts()
        {
            this.OrdersProducts = new HashSet<OrdersProducts>();
        }
    
        public string artikul { get; set; }
        public string nameProducts { get; set; }
        public string capacity { get; set; }
        public decimal cost { get; set; }
        public string postav { get; set; }
        public string proisvod { get; set; }
        public int category { get; set; }
        public int descount { get; set; }
        public int countInStorage { get; set; }
        public string opisav { get; set; }
        public string photo { get; set; }

        public string imageCorrect
        {
            get
            {
                if (photo != null) return "/content/" + photo;
                else return null;
            }
        }

        public string correctCat
        {
            get
            {
                return Categorys.categoryName;
            }
        }

        public Visibility VisibleBtn
        {
            get
            {
                if (VisibleUsers.currentUsers == "Администратор") return Visibility.Visible;
                else return Visibility.Hidden;
            }
        }

        public string back
        {
            get
            {
                if (descount > 17) return "#FFDEAD";
                if (countInStorage == 0) return "Cyan";
                else return "White";
            }
        }

        public string OldCost
        {
            get
            {
                if (descount == 0) return "";
                else return cost.ToString();
            }
        }
        public double NewCost
        {
            get 
            {
                if (descount == 0) return (double)cost;
                else return ((double)cost - ((double)cost * (double)descount / 100));
            }
        }


        public virtual Categorys Categorys { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdersProducts> OrdersProducts { get; set; }
    }
}
