//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace trenimLast
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class Users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Users()
        {
            this.Orders = new HashSet<Orders>();
        }
    
        public int id { get; set; }
        public int rolys { get; set; }
        public string lastName { get; set; }
        public string firstName { get; set; }
        public string otchest { get; set; }
        public string login { get; set; }
        public string passwrod { get; set; }

        public string correctRoly
        {
            get
            {
                var rol = trenimLastEntities.GetContext().Rolys.FirstOrDefault(r => r.id == rolys);
                return rol.rolyName;
            }
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders> Orders { get; set; }
        public virtual Rolys Rolys1 { get; set; }
    }
}
